# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bradley/Dev/ScallopShell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bradley/Dev/ScallopShell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bradley/Dev/ScallopShell/CMakeFiles /home/bradley/Dev/ScallopShell//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bradley/Dev/ScallopShell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/bradley/Dev/ScallopShell/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eventhandler

# Build rule for target.
eventhandler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventhandler
.PHONY : eventhandler

# fast build rule for target.
eventhandler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/build
.PHONY : eventhandler/fast

#=============================================================================
# Target rules for targets named scallop

# Build rule for target.
scallop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scallop
.PHONY : scallop

# fast build rule for target.
scallop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scallop.dir/build.make CMakeFiles/scallop.dir/build
.PHONY : scallop/fast

src/libsrc/asm_dump.o: src/libsrc/asm_dump.cpp.o
.PHONY : src/libsrc/asm_dump.o

# target to build an object file
src/libsrc/asm_dump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/asm_dump.cpp.o
.PHONY : src/libsrc/asm_dump.cpp.o

src/libsrc/asm_dump.i: src/libsrc/asm_dump.cpp.i
.PHONY : src/libsrc/asm_dump.i

# target to preprocess a source file
src/libsrc/asm_dump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/asm_dump.cpp.i
.PHONY : src/libsrc/asm_dump.cpp.i

src/libsrc/asm_dump.s: src/libsrc/asm_dump.cpp.s
.PHONY : src/libsrc/asm_dump.s

# target to generate assembly for a file
src/libsrc/asm_dump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/asm_dump.cpp.s
.PHONY : src/libsrc/asm_dump.cpp.s

src/libsrc/core.o: src/libsrc/core.cpp.o
.PHONY : src/libsrc/core.o

# target to build an object file
src/libsrc/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/core.cpp.o
.PHONY : src/libsrc/core.cpp.o

src/libsrc/core.i: src/libsrc/core.cpp.i
.PHONY : src/libsrc/core.i

# target to preprocess a source file
src/libsrc/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/core.cpp.i
.PHONY : src/libsrc/core.cpp.i

src/libsrc/core.s: src/libsrc/core.cpp.s
.PHONY : src/libsrc/core.s

# target to generate assembly for a file
src/libsrc/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/core.cpp.s
.PHONY : src/libsrc/core.cpp.s

src/libsrc/gui.o: src/libsrc/gui.cpp.o
.PHONY : src/libsrc/gui.o

# target to build an object file
src/libsrc/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/gui.cpp.o
.PHONY : src/libsrc/gui.cpp.o

src/libsrc/gui.i: src/libsrc/gui.cpp.i
.PHONY : src/libsrc/gui.i

# target to preprocess a source file
src/libsrc/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/gui.cpp.i
.PHONY : src/libsrc/gui.cpp.i

src/libsrc/gui.s: src/libsrc/gui.cpp.s
.PHONY : src/libsrc/gui.s

# target to generate assembly for a file
src/libsrc/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/gui.cpp.s
.PHONY : src/libsrc/gui.cpp.s

src/libsrc/jump.o: src/libsrc/jump.cpp.o
.PHONY : src/libsrc/jump.o

# target to build an object file
src/libsrc/jump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/jump.cpp.o
.PHONY : src/libsrc/jump.cpp.o

src/libsrc/jump.i: src/libsrc/jump.cpp.i
.PHONY : src/libsrc/jump.i

# target to preprocess a source file
src/libsrc/jump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/jump.cpp.i
.PHONY : src/libsrc/jump.cpp.i

src/libsrc/jump.s: src/libsrc/jump.cpp.s
.PHONY : src/libsrc/jump.s

# target to generate assembly for a file
src/libsrc/jump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/jump.cpp.s
.PHONY : src/libsrc/jump.cpp.s

src/libsrc/loop.o: src/libsrc/loop.cpp.o
.PHONY : src/libsrc/loop.o

# target to build an object file
src/libsrc/loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/loop.cpp.o
.PHONY : src/libsrc/loop.cpp.o

src/libsrc/loop.i: src/libsrc/loop.cpp.i
.PHONY : src/libsrc/loop.i

# target to preprocess a source file
src/libsrc/loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/loop.cpp.i
.PHONY : src/libsrc/loop.cpp.i

src/libsrc/loop.s: src/libsrc/loop.cpp.s
.PHONY : src/libsrc/loop.s

# target to generate assembly for a file
src/libsrc/loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/loop.cpp.s
.PHONY : src/libsrc/loop.cpp.s

src/libsrc/search.o: src/libsrc/search.cpp.o
.PHONY : src/libsrc/search.o

# target to build an object file
src/libsrc/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/search.cpp.o
.PHONY : src/libsrc/search.cpp.o

src/libsrc/search.i: src/libsrc/search.cpp.i
.PHONY : src/libsrc/search.i

# target to preprocess a source file
src/libsrc/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/search.cpp.i
.PHONY : src/libsrc/search.cpp.i

src/libsrc/search.s: src/libsrc/search.cpp.s
.PHONY : src/libsrc/search.s

# target to generate assembly for a file
src/libsrc/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/search.cpp.s
.PHONY : src/libsrc/search.cpp.s

src/libsrc/watch.o: src/libsrc/watch.cpp.o
.PHONY : src/libsrc/watch.o

# target to build an object file
src/libsrc/watch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/watch.cpp.o
.PHONY : src/libsrc/watch.cpp.o

src/libsrc/watch.i: src/libsrc/watch.cpp.i
.PHONY : src/libsrc/watch.i

# target to preprocess a source file
src/libsrc/watch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/watch.cpp.i
.PHONY : src/libsrc/watch.cpp.i

src/libsrc/watch.s: src/libsrc/watch.cpp.s
.PHONY : src/libsrc/watch.s

# target to generate assembly for a file
src/libsrc/watch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eventhandler.dir/build.make CMakeFiles/eventhandler.dir/src/libsrc/watch.cpp.s
.PHONY : src/libsrc/watch.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scallop.dir/build.make CMakeFiles/scallop.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scallop.dir/build.make CMakeFiles/scallop.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scallop.dir/build.make CMakeFiles/scallop.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... eventhandler"
	@echo "... scallop"
	@echo "... src/libsrc/asm_dump.o"
	@echo "... src/libsrc/asm_dump.i"
	@echo "... src/libsrc/asm_dump.s"
	@echo "... src/libsrc/core.o"
	@echo "... src/libsrc/core.i"
	@echo "... src/libsrc/core.s"
	@echo "... src/libsrc/gui.o"
	@echo "... src/libsrc/gui.i"
	@echo "... src/libsrc/gui.s"
	@echo "... src/libsrc/jump.o"
	@echo "... src/libsrc/jump.i"
	@echo "... src/libsrc/jump.s"
	@echo "... src/libsrc/loop.o"
	@echo "... src/libsrc/loop.i"
	@echo "... src/libsrc/loop.s"
	@echo "... src/libsrc/search.o"
	@echo "... src/libsrc/search.i"
	@echo "... src/libsrc/search.s"
	@echo "... src/libsrc/watch.o"
	@echo "... src/libsrc/watch.i"
	@echo "... src/libsrc/watch.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/bradley/Dev/ScallopShell/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

